// <auto-generated/>
#pragma warning disable 1591
namespace GoTorz.Components.Pages
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
#nullable restore
#line 2 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\Pages\Weather.razor"
           [StreamRendering]

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Components.RouteAttribute("/weather")]
    #nullable restore
    public partial class Weather : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((global::System.Action)(() => {
// language=Route,Component
#nullable restore
#line 1 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\Pages\Weather.razor"
global::System.Object __typeHelper = "/weather";

#line default
#line hidden
#nullable disable
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line 10 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\Pages\Weather.razor"
 if (forecasts == null)
{
    

#line default
#line hidden
#nullable disable
#nullable restore
#line 12 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\Pages\Weather.razor"
                              
}
else
{
    

#line default
#line hidden
#nullable disable
#nullable restore
#line 26 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\Pages\Weather.razor"
             foreach (var forecast in forecasts)
            {
                

#line default
#line hidden
#nullable disable
#nullable restore
#line 29 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\Pages\Weather.razor"
                   __o = forecast.Date.ToShortDateString();

#line default
#line hidden
#nullable disable
#nullable restore
#line 30 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\Pages\Weather.razor"
                   __o = forecast.TemperatureC;

#line default
#line hidden
#nullable disable
#nullable restore
#line 31 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\Pages\Weather.razor"
                   __o = forecast.TemperatureF;

#line default
#line hidden
#nullable disable
#nullable restore
#line 32 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\Pages\Weather.razor"
                   __o = forecast.Summary;

#line default
#line hidden
#nullable disable
#nullable restore
#line 33 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\Pages\Weather.razor"
                     
            }

#line default
#line hidden
#nullable disable
#nullable restore
#line 36 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\Pages\Weather.razor"
            
}

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
#nullable restore
#line 39 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\Pages\Weather.razor"
       
    private WeatherForecast[]? forecasts;

    protected override async Task OnInitializedAsync()
    {
        // Simulate asynchronous loading to demonstrate streaming rendering
        await Task.Delay(500);

        var startDate = DateOnly.FromDateTime(DateTime.Now);
        var summaries = new[] { "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching" };
        forecasts = Enumerable.Range(1, 5).Select(index => new WeatherForecast
        {
            Date = startDate.AddDays(index),
            TemperatureC = Random.Shared.Next(-20, 55),
            Summary = summaries[Random.Shared.Next(summaries.Length)]
        }).ToArray();
    }

    private class WeatherForecast
    {
        public DateOnly Date { get; set; }
        public int TemperatureC { get; set; }
        public string? Summary { get; set; }
        public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
    }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
