// <auto-generated/>
#pragma warning disable 1591
namespace GoTorz.Components
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\_Imports.razor"
using System.Net.Http;

#nullable disable
#nullable restore
#line 2 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\_Imports.razor"
using System.Net.Http.Json;

#nullable disable
#nullable restore
#line 3 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#nullable disable
#nullable restore
#line 4 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#nullable disable
#nullable restore
#line 5 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#nullable disable
#nullable restore
#line 6 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\_Imports.razor"
using static Microsoft.AspNetCore.Components.Web.RenderMode;

#nullable disable
#nullable restore
#line 7 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization;

#nullable disable
#nullable restore
#line 8 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\_Imports.razor"
using Microsoft.JSInterop;

#nullable disable
#nullable restore
#line 9 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\_Imports.razor"
using GoTorz;

#nullable disable
#nullable restore
#line 10 "C:\Users\Troels\AppData\Local\Temp\3BBC141DF4E9F82ADBC9E3ED3DC057249F17\2\GoTorz\GoTorz\Components\_Imports.razor"
using GoTorz.Components;

#line default
#line hidden
#nullable disable
    #nullable restore
    public partial class _Imports : System.Object
    #nullable disable
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        protected void Execute()
        {
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
